services:
  postgres:
    image: postgres:16-alpine
    container_name: pesaschile-quote-service-postgres
    environment:
      POSTGRES_DB: pesaschile_quote_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pesaschile_quote_service"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
