/** Recipient-injection and malformed payloads (pre-flight audit §27; the first one was proven against the V1 normalizer). */
export const HOSTILE_RECIPIENTS = [
  "a>,<victim@evil.com",
  "x@y.com>,<v@evil.com",
  "x@y.com,z@w.com",
  "x@y.com;z@w.com",
  "x@y.com z@w.com",
  "a b@c.com",
  " a@c.com",
  "a@c.com ",
  "a@b.com\r\nBcc: victim@evil.com",
  "a@b.com\nBcc: victim@evil.com",
  "a\tb@c.com",
  "<a@b.com>",
  "Name <a@b.com>",
  '"a"@b.com',
  'a"b@c.com',
  "a(b)@c.com",
  "a[b]@c.com",
  "a@[1.2.3.4]",
  "a\\b@c.com",
  "a:b@c.com",
  "a@b@c.com",
  "a@b",
  "@b.com",
  "a@",
  "a..b@c.com",
  "",
  `${"a".repeat(250)}@b.com`
];
