// GENERATED by scripts/generate-migration-manifest.cjs (npm run db:manifest). Do not edit.
// The last entry is the expected schema head. Changing a migration file
// changes its checksum: historical migrations must never be edited.

export interface MigrationManifestEntry {
  readonly name: string;
  readonly sha256: string;
}

export const MIGRATION_MANIFEST: readonly MigrationManifestEntry[] = [
  { name: "000001_baseline", sha256: "f5d305fb5de63e5930452823c809ecfbb990d5deba2996aa85643b0082e34971" },
  { name: "000002_quote_persistence", sha256: "830b5d36f83c3ee2f8a4195fcf586beeb6298e6c9c77c5c4adc85dfd4374c682" },
  { name: "000003_quote_email_delivery", sha256: "f11f8eeb996eff94efe27cc5074d753234591ce39c364131ddb560f9ffb61218" },
  { name: "000004_quote_line_external_identity", sha256: "027dbfc31e5e79770a00733bd92e01b496333ead1f4b0993960ed718fba9e02b" },
  { name: "000005_quote_line_shipping", sha256: "1d142aa26edec4127bd7d81c03f14d149456852c22d2c7dd119f0e6130cec12c" },
  { name: "000006_migration_integrity", sha256: "b365fc8bbb105e6efa970a647a83c37a8c11486e5da3cfdb3d88bb5097c15258" },
  { name: "000007_quote_v2_persistence", sha256: "b9ed8d0736dc77b2c6542b6252a1b8962b8d57673a02869af16fd5789b5d71ca" },
  { name: "000008_quote_v2_runtime_grants", sha256: "d67ec4e0e5ddccd01510108318d5baa4db951ffc02acf080561e27087c4c3162" }
];
